name: Pull Request
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  lint:
    name: "Lint with golangci-lint"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Configure git for private modules (go get)
        run: |
          git config --global url."https://paluszkiewiczB:${{ secrets.PERSONAL_ACCESS_KEY }}@github.com".insteadOf "https://github.com"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
  build-and-test:
    name: "Build and run unit tests"
    runs-on: ubuntu-latest
    steps:
      - name: Configure git for private modules (go get)
        run: |
          git config --global url."https://paluszkiewiczB:${{ secrets.PERSONAL_ACCESS_KEY }}@github.com".insteadOf "https://github.com"
      - name: checkout
        uses: actions/checkout@v2
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: go get
        run: go get ./...
      - name: go build
        run: go build ./...
      - name: go test
        run: go test ./...
  code-coverage:
    name: "Measure code coverage"
    runs-on: ubuntu-latest
    steps:
      - name: Configure git for private modules (go get)
        run: |
          git config --global url."https://paluszkiewiczB:${{ secrets.PERSONAL_ACCESS_KEY }}@github.com".insteadOf "https://github.com"
      - name: checkout
        uses: actions/checkout@v2
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: go get
        run: go get ./...
      - name: Generate coverage report
        run: |
          go test `go list ./... | grep -v examples` -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage report
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella