name: Pull Request
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  lint:
    name: "Lint with golangci-lint"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Configure git for private modules (go get)
        run: |
          git config --global url."https://paluszkiewiczB:${{ secrets.PERSONAL_ACCESS_KEY }}@github.com".insteadOf "https://github.com"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          working-directory: ${{ matrix.projects }}
  build-and-test:
    name: "Build and run unit tests"
    runs-on: ubuntu-latest
    steps:
      - name: Configure git for private modules (go get)
        run: |
          git config --global url."https://paluszkiewiczB:${{ secrets.PERSONAL_ACCESS_KEY }}@github.com".insteadOf "https://github.com"
      - name: checkout
        uses: actions/checkout@v2
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: go build
        working-directory: ${{ matrix.projects }}
        run: go build
      - name: go test
        working-directory: ${{ matrix.projects }}
        run: go test ./...